name: Ruff Code Quality Check

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  ruff-check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install ruff
      run: pip install ruff

    - name: Run ruff check
      run: ruff check git/src/

    - name: Run ruff format check
      run: ruff format --check git/src/
